language: ruby
rvm:
  - 1.8.7-p374
  - 1.9.2-p330
  - 1.9.3-p551
  - 2.0.0-p648
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - jruby-18mode
  - jruby-19mode
  - jruby-9.1.12.0
sudo: false
before_script:
- if (ruby -e "exit RUBY_VERSION.to_f >= 2.4"); then export RUBYOPT="--enable-frozen-string-literal"; fi; echo $RUBYOPT
